baseUrl = "https://jira.your.com"
authConfigPath = "auth.toml"
ignoreSsl = false

[[actions]]
jql = 'labels = "my_label"'

removeLabels = ["label-1", "label-2"]
addLabels = ["new-label-1", "new-label-2"]


[[actions]]
jql = 'labels = "my_label"'

addLabels = ["new-label-1", "new-label-2"]

[[actions]]
jql = 'labels = "my_label"'
